[tools]
node = ["lts", "latest"]
"npm:@antfu/ni" = "latest"
zig = "latest"
bun = "latest"
deno = "latest"
"npm:nypm" = "latest"
npm = "latest"
usage = "latest"
slsa-verifier = "latest"
cosign = "latest"

[settings]
experimental = true


###########
# ENVIRONMENT
###########

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

###########
# HOOKS
###########

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'